import './css/section-faq.css';

import { Accordion } from 'react-bootstrap';

const SectionFAQ = () => {
  return (
    <section className="section-faq" id="faq">
      <div className="heading-container">
        <h2 className="heading-secondary text-gradient">FAQ</h2>
      </div>
      <Accordion defaultActiveKey="0" flush>
        <Accordion.Item eventKey="0">
          <Accordion.Header className="gradient-btn">
            What is the Ice Bear NFT?
          </Accordion.Header>
          <Accordion.Body>
            <p>
              A collection of 3D rendered artwork generated by an algorithm
              based on Ice Bears which are going extinct in the regions of
              Artic. The Ice Bear NFT is available in various collections such
              as classic, founders, and limited edition. We strive to generate
              more artwork to build long-term community.
            </p>
          </Accordion.Body>
        </Accordion.Item>
        <Accordion.Item eventKey="1">
          <Accordion.Header className="gradient-btn">
            What is the Commercial Rights?
          </Accordion.Header>
          <Accordion.Body>
            <p>
              Commercial rights to use the NFT you own in games, animated
              series, comics, apparel, merchandise or anything else you can
              think of.
            </p>
          </Accordion.Body>
        </Accordion.Item>
        <Accordion.Item eventKey="2">
          <Accordion.Header className="gradient-btn">
            What is our NFT tiers?
          </Accordion.Header>
          <Accordion.Body>
            <p>
              Our NFT tiers include Common, Rare, Epic, Legendary and Founders.
            </p>
          </Accordion.Body>
        </Accordion.Item>
        <Accordion.Item eventKey="3">
          <Accordion.Header className="gradient-btn">
            Do we save the Ice Bears ?
          </Accordion.Header>
          <Accordion.Body>
            <p>
              Yes we do since we are pledged towards saving the ice bears from
              our revenue made from the NFTs sold.
            </p>
          </Accordion.Body>
        </Accordion.Item>
        <Accordion.Item eventKey="4">
          <Accordion.Header className="gradient-btn">
            How many NFT's will be launched?
          </Accordion.Header>
          <Accordion.Body>
            <p>3333 NFT's</p>
          </Accordion.Body>
        </Accordion.Item>
        <Accordion.Item eventKey="5">
          <Accordion.Header className="gradient-btn">
            What is the Mint Price ?
          </Accordion.Header>
          <Accordion.Body>
            <p>TBH, Trust us won't take long to decide!</p>
          </Accordion.Body>
        </Accordion.Item>
        
      </Accordion>
    </section>
  );
};

export default SectionFAQ;
